### ISSUE TITLE
Omit QBE

### ISSUE THREAD

**Issue by vlasakm** [wdv4758h/awesome-jit#9]
I don't think I would have recommended QBE for JITs. It's great, but it is designed as a simple ahead of time compiler and it shows:

 - A standalone binary. It isn't a library and doesn't have an API.
 - The input is QBE IR in textual form.
 - The output is textual assembly intended for the system assembler and linker.

Since this awesome list is about JITs I don't think QBE should be listed. Yes QBE can be an inspiration for a custom code generator, but even if I went with a custom code generator my first concern would be instruction encoding (so I can actually run the code), and QBE doesn't help with that.

Thoughts?

**Comment by wdv4758h** [comment]
I see your concern. I've moved the QBE out and leave it in the bottom. Still keep it for now, since many people mentioned it. But I marked it as "not designed for JIT", with a link to sourcehut discussion that it's not suitable for JIT out of the box.

Feel free to have other feedback!
